import RegisterForm from "@/components/RegisterForm";

export default function Home() {
  return (
    <div className="min-h-screen bg-gray-50 flex flex-col items-center justify-center p-4 font-[family-name:var(--font-geist-sans)]">
      <main className="w-full max-w-4xl flex flex-col items-center gap-8">
        <div className="text-center">
          <h1 className="text-4xl font-extrabold tracking-tight text-gray-900 sm:text-5xl">
            Autonomous Template
          </h1>
          <p className="mt-4 text-lg text-gray-600">
            Hexagonal Go Backend + Next.js App Router + Tailwind CSS
          </p>
        </div>

        <div className="w-full max-w-md">
          <RegisterForm />
        </div>

        <div className="mt-12 grid grid-cols-1 gap-4 sm:grid-cols-2 lg:grid-cols-3 w-full">
          <FeatureCard 
            title="Layer Isolation" 
            desc="Enforced via depguard. Domain has zero dependencies." 
          />
          <FeatureCard 
            title="Type Bridge" 
            desc="Go DTOs automatically compiled to TypeScript via tygo." 
          />
          <FeatureCard 
            title="DB Generation" 
            desc="Type-safe DB access generated by sqlc from raw SQL." 
          />
        </div>
      </main>
    </div>
  );
}

function FeatureCard({ title, desc }: { title: string; desc: string }) {
  return (
    <div className="bg-white p-6 rounded-xl shadow-sm border border-gray-100">
      <h3 className="text-lg font-semibold text-gray-900">{title}</h3>
      <p className="mt-2 text-sm text-gray-500">{desc}</p>
    </div>
  );
}
